-- ═══════════════════════════════════════════════════════════════════
-- GuEventorganizer — Seed Data
-- Run this AFTER schema.sql in Supabase Dashboard → SQL Editor
-- ═══════════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────
-- VENUES (from mockData.js)
-- ─────────────────────────────────────────────────
INSERT INTO public.venues (name, capacity, type, status, image, amenities, floor, building) VALUES
  ('New Auditorium', 1500, 'Auditorium', 'available', '/new-auditorium.jpg', ARRAY['Projector', 'Sound System', 'AC', 'Stage Lighting', 'Green Room'], 'Ground Floor', 'Main Campus'),
  ('Old Auditorium', 500, 'Auditorium', 'available', '/old-auditorium.jpg', ARRAY['Projector', 'Sound System', 'AC', 'WiFi'], 'Ground Floor', 'Main Campus'),
  ('AIDS Library', 200, 'Library Hall', 'available', '/aids-library.jpg', ARRAY['Projector', 'Whiteboard', 'AC', 'WiFi', 'Computers'], '1st Floor', 'AIDS Block'),
  ('Main Ground', 5000, 'Outdoor', 'available', '/main-ground.png', ARRAY['Floodlights', 'Seating', 'Pavilion', 'Changing Rooms'], 'Ground', 'Sports Complex'),
  ('Open Concert Area', 3000, 'Outdoor', 'available', '/open-concert-area.jpg', ARRAY['Stage', 'Sound System', 'Lighting', 'Open Seating'], 'Ground', 'Main Campus'),
  ('Cricket Ground', 3000, 'Outdoor', 'available', '/cricket-ground.jpg', ARRAY['Floodlights', 'Pavilion', 'Pitch', 'Seating', 'Scoreboard'], 'Ground', 'Sports Complex'),
  ('iOS Lab', 60, 'Lab', 'available', '/ios-lab.jpg', ARRAY['iMacs', 'Projector', 'AC', 'High-Speed Internet', 'Xcode Stations'], '3rd Floor', 'Main Campus'),
  ('Code Arena', 120, 'Lab', 'available', '/code-arena.jpg', ARRAY['Computers', 'Projector', 'AC', 'High-Speed Internet', 'Intel AI Lab', 'Library'], '2nd Floor', 'Main Campus');


-- ─────────────────────────────────────────────────
-- CLUBS (from mockData.js — all 24)
-- ─────────────────────────────────────────────────
INSERT INTO public.clubs (name, description, members, logo, abbr, color, events_count, category) VALUES
  ('Quizzard', 'The official quiz club of Galgotias University. Sharpen your knowledge across domains through weekly quizzes, inter-college competitions, and brain-teasing events.', 380, '/clubs/quizzard.png', 'QZ', 'from-purple-600 to-blue-500', 22, 'Knowledge'),
  ('Scintillations', 'The fashion and beauty society celebrating elegance, creativity, and style through fashion shows, makeover workshops, and glamour events.', 290, '/clubs/scintillations.png', 'SC', 'from-pink-500 to-rose-600', 14, 'Cultural'),
  ('Stage Management Team', 'The backbone of every event — handling stage setup, sound engineering, lighting design, and event production for all university programs.', 120, '/clubs/smt.png', 'SMT', 'from-gray-700 to-gray-900', 40, 'Management'),
  ('Sponsorship Club', 'Building industry partnerships and securing sponsorships for university events. Learn negotiation, marketing, and corporate relations.', 150, '/clubs/sponsorship.png', 'SP', 'from-slate-600 to-slate-800', 10, 'Management'),
  ('TechnoJam', 'The premier tech community at Galgotias. Workshops on coding, hackathons, open-source contributions, and tech talks by industry experts.', 520, '/clubs/technojam.png', 'TJ', 'from-cyan-500 to-blue-600', 32, 'Technical'),
  ('The Humanity Saviours', 'We do what we can do — a social welfare society organizing blood drives, plantation drives, awareness campaigns, and community outreach programs.', 340, '/clubs/humanitysaviours.png', 'THS', 'from-teal-500 to-emerald-600', 20, 'Social'),
  ('OP', 'The official podcast and media club producing campus stories, student interviews, and creative audio-visual content for the university community.', 180, '/clubs/op.png', 'OP', 'from-fuchsia-500 to-purple-600', 16, 'Media'),
  ('Panache', 'The fashion and lifestyle club organizing fashion walks, styling workshops, and the annual Galgotias Fashion Week. Where style meets substance.', 350, '/clubs/panache.png', 'PN', 'from-amber-400 to-yellow-600', 12, 'Cultural'),
  ('Galgotias Marketing Team', 'Promoting university events through creative marketing strategies, digital campaigns, social media management, and branding initiatives.', 200, NULL, 'GMT', 'from-red-500 to-red-700', 18, 'Management'),
  ('Note Veda', 'The Music Club of Galgotias — jamming sessions, live performances, music production workshops, and organizing the annual music festival.', 280, '/clubs/noteveda.png', 'NV', 'from-gray-800 to-black', 24, 'Cultural'),
  ('Galgotias Dance Crew', 'From classical to hip-hop, contemporary to Bollywood — the official dance crew performing at university events and competing nationally.', 220, '/clubs/dancecrew.png', 'GDC', 'from-green-500 to-emerald-600', 20, 'Cultural'),
  ('G-Post', 'The university editorial and journalism club covering campus news, student stories, creative writing, and publishing the official newsletter.', 160, '/clubs/gpost.png', 'GP', 'from-blue-800 to-red-700', 14, 'Literary'),
  ('GU Management Team', 'The event management powerhouse coordinating logistics, crowd management, and operations for all major university events and fests.', 175, NULL, 'GUMT', 'from-gray-600 to-gray-800', 35, 'Management'),
  ('Humans of Galgotias', 'Storytelling series capturing the diverse voices and inspiring journeys of students, faculty, and staff at Galgotias University.', 130, '/clubs/hog.png', 'HOG', 'from-orange-400 to-yellow-500', 8, 'Media'),
  ('Kalila', 'The creative arts and psychology club exploring the intersection of art, mental wellness, and self-expression through creative workshops.', 190, NULL, 'KL', 'from-amber-600 to-orange-700', 12, 'Cultural'),
  ('Lingo Freaks', 'The language and literature club celebrating linguistic diversity through debates, poetry slams, storytelling, and multilingual events.', 210, '/clubs/lingofreaks.png', 'LF', 'from-blue-400 to-indigo-600', 16, 'Literary'),
  ('Cam Circle', 'The photography and videography club capturing campus life, conducting photo walks, editing workshops, and annual photography exhibitions.', 240, '/clubs/camcircle.png', 'CC', 'from-blue-600 to-cyan-600', 18, 'Media'),
  ('Cyber Cell', 'Cybersecurity awareness, ethical hacking workshops, CTF competitions, and building a safer digital community at Galgotias.', 310, '/clubs/cybercell.png', 'CYB', 'from-red-500 to-orange-500', 15, 'Technical'),
  ('FRAG', 'The gaming and esports club hosting LAN parties, gaming tournaments, esports leagues, and game development workshops.', 420, '/clubs/frag.png', 'FR', 'from-gray-700 to-black', 22, 'Gaming'),
  ('Graphex', 'The Design Club — graphic design, UI/UX, digital art workshops, design sprints, and creating visual content for university events.', 260, '/clubs/graphex-new.png', 'GX', 'from-indigo-500 to-purple-600', 14, 'Technical'),
  ('The Actor''s Hub', 'Theatre, drama, and performing arts society staging plays, street theatre, improvisational comedy, and the annual drama festival.', 180, '/clubs/actorshub.png', 'TAH', 'from-red-800 to-amber-900', 16, 'Cultural'),
  ('Artistico', 'Fine arts, calligraphy, sketching, painting, and sculpture — the hub for visual artists to create, learn, and exhibit their work.', 170, '/clubs/artistico.png', 'ART', 'from-red-500 to-black', 10, 'Cultural'),
  ('Galgotias Book Club', 'All Booked — reading circles, author meets, book reviews, literary discussions, and building a culture of reading on campus.', 140, NULL, 'GBC', 'from-yellow-500 to-amber-600', 12, 'Literary'),
  ('Business Club', 'Igniting innovation, fostering entrepreneurship — case study competitions, startup incubation, business simulations, and industry visits.', 280, NULL, 'BC', 'from-slate-500 to-gray-700', 16, 'Management');


-- ─────────────────────────────────────────────────
-- EVENTS (from mockData.js — all 12)
-- Note: created_by is NULL since these are seed events
-- ─────────────────────────────────────────────────
INSERT INTO public.events (title, description, category, venue, date, end_date, time, organizer, department, registrations, max_capacity, status, approval_status, featured, poster, gallery, tags) VALUES
  ('HackGU 2026', 'Annual 36-hour hackathon at Galgotias University. Build innovative solutions for real-world problems.', 'Hackathons', 'New Auditorium', '2026-05-20', '2026-05-21', '09:00 AM', 'Technical Society', 'CSE', 342, 500, 'upcoming', 'approved', true, '/hackgu-1.jpg', ARRAY['/hackgu-1.jpg', '/hackgu-2.jpg', '/hackgu-3.jpg', '/hackgu-4.jpg'], ARRAY['coding', 'innovation', 'prizes']),
  ('Crescendo - Cultural Fest', 'The biggest cultural extravaganza featuring music, dance, drama, and art competitions.', 'Cultural', 'Open Concert Area', '2026-06-05', '2026-06-07', '10:00 AM', 'Cultural Committee', 'All Departments', 890, 1200, 'upcoming', 'approved', true, '/events/unifest.jpg', NULL, ARRAY['music', 'dance', 'art']),
  ('AI/ML Workshop', 'Hands-on workshop on Machine Learning with Python, TensorFlow, and real datasets.', 'Workshops', 'AIDS Library', '2026-05-15', '2026-05-15', '02:00 PM', 'Coding Club', 'CSE', 120, 150, 'upcoming', 'approved', false, 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800', NULL, ARRAY['AI', 'ML', 'Python']),
  ('Inter-University Cricket Tournament', 'Annual cricket tournament featuring teams from top universities across NCR.', 'Sports', 'Main Ground', '2026-05-25', '2026-05-28', '07:00 AM', 'Sports Committee', 'Physical Education', 180, 200, 'upcoming', 'approved', true, 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800', NULL, ARRAY['cricket', 'sports', 'tournament']),
  ('Blockchain Seminar', 'Expert talk on blockchain technology, Web3, and decentralized applications.', 'Seminars', 'Open Concert Area', '2026-05-12', '2026-05-12', '11:00 AM', 'E-Cell', 'CSE', 85, 100, 'upcoming', 'approved', false, 'https://images.unsplash.com/photo-1639762681057-408e52192e55?w=800', NULL, ARRAY['blockchain', 'web3', 'crypto']),
  ('RoboWars 3.0', 'Build and battle robots in this thrilling robotics competition with exciting prizes.', 'Technical', 'Code Arena', '2026-06-10', '2026-06-10', '10:00 AM', 'Robotics Club', 'ECE', 64, 80, 'upcoming', 'approved', true, 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800', NULL, ARRAY['robotics', 'engineering', 'competition']),
  ('Photography Walk', 'Campus photography expedition to capture the beauty of Galgotias University.', 'Cultural', 'Campus Wide', '2026-05-18', '2026-05-18', '06:00 AM', 'Photography Club', 'All', 45, 60, 'upcoming', 'approved', false, 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800', NULL, ARRAY['photography', 'campus', 'art']),
  ('Startup Pitch Night', 'Present your startup ideas to industry mentors and investors. Win seed funding!', 'Seminars', 'Old Auditorium', '2026-05-30', '2026-05-30', '05:00 PM', 'Entrepreneurship Cell', 'Management', 55, 75, 'upcoming', 'approved', false, 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800', NULL, ARRAY['startup', 'pitch', 'entrepreneurship']),
  ('CodeSprint Challenge', '3-hour competitive programming contest with problems from easy to expert level.', 'Technical', 'Code Arena', '2026-04-20', '2026-04-20', '02:00 PM', 'Coding Club', 'CSE', 200, 200, 'completed', 'approved', false, 'https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=800', NULL, ARRAY['coding', 'competitive', 'programming']),
  ('TT Hustle 2.0', 'The ultimate table tennis showdown! Intense singles and doubles matches across campus.', 'Sports', 'New Auditorium', '2026-04-10', '2026-04-12', '10:00 AM', 'Sports Committee', 'All', 320, 400, 'completed', 'approved', true, '/tt-hustle-1.jpg', ARRAY['/tt-hustle-1.jpg', '/tt-hustle-2.jpg', '/tt-hustle-3.jpg'], ARRAY['table-tennis', 'sports', 'tournament']),
  ('Cloud Computing Workshop', 'Learn AWS, Azure, and GCP fundamentals with hands-on labs and certifications.', 'Workshops', 'Old Auditorium', '2026-06-15', '2026-06-16', '10:00 AM', 'Technical Society', 'CSE', 95, 120, 'upcoming', 'approved', false, 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800', NULL, ARRAY['cloud', 'AWS', 'devops']),
  ('TEDxGalgotias', 'Ideas worth spreading - featuring speakers from tech, arts, science, and social impact.', 'Seminars', 'New Auditorium', '2026-06-20', '2026-06-20', '09:30 AM', 'Student Council', 'All', 410, 500, 'upcoming', 'approved', true, '/events/seminar.jpg', NULL, ARRAY['TEDx', 'talks', 'inspiration']);


-- ─────────────────────────────────────────────────
-- EVENT_DETAILS (from eventDetails.js — all 12)
-- ─────────────────────────────────────────────────
INSERT INTO public.event_details (event_id, long_description, eligibility, schedule, prizes, rules, coordinator_name, coordinator_phone, coordinator_email, whatsapp_group) VALUES
  (1, 'HackGU 2026 is the flagship hackathon of Galgotias University, bringing together 500+ brilliant minds to build innovative solutions over 36 non-stop hours.', 'Open to all current students. Teams of 2–4 members from any department.', '[{"time":"09:00 AM","activity":"Opening Ceremony & Theme Reveal"},{"time":"10:00 AM","activity":"Hacking Begins"},{"time":"01:00 PM","activity":"Lunch Break & Networking"},{"time":"06:00 PM","activity":"Mentor Sessions Round 1"},{"time":"09:00 AM (Day 2)","activity":"Final Submissions"},{"time":"02:00 PM (Day 2)","activity":"Prize Distribution & Closing"}]', '[{"place":"🥇 1st Place","reward":"₹50,000 + Internship Offers"},{"place":"🥈 2nd Place","reward":"₹30,000 + Goodies"},{"place":"🥉 3rd Place","reward":"₹15,000 + Certificates"},{"place":"🎨 Best UI/UX","reward":"₹5,000 Special Prize"}]', ARRAY['Teams of 2–4 members only', 'All code must be written during the hackathon', 'Open-source libraries permitted', 'One submission per team', 'Plagiarism = disqualification'], 'Rahul Kapoor', '+91 98765 43210', 'hackgu@galgotias.edu.in', 'https://chat.whatsapp.com/hackgu2026'),
  (2, 'Crescendo is the annual 3-day cultural fest — a vibrant celebration of art, music, dance, fashion, and theatre.', 'Open to all students with valid university ID. Inter-college participants welcome with prior registration.', '[{"time":"10:00 AM","activity":"Inauguration & Lamp Lighting"},{"time":"11:00 AM","activity":"Battle of Bands (Prelims)"},{"time":"02:00 PM","activity":"Street Play Competition"},{"time":"04:00 PM","activity":"Fashion Show"},{"time":"07:00 PM","activity":"DJ Night & Celebrity Performance"}]', '[{"place":"🎸 Best Band","reward":"₹25,000"},{"place":"💃 Best Dance Crew","reward":"₹20,000"},{"place":"🎭 Best Actor","reward":"₹10,000"}]', ARRAY['Carry university ID at all times', 'No outside food or beverages', 'Follow event-specific rules'], 'Sneha Joshi', '+91 87654 32109', 'crescendo@galgotias.edu.in', NULL),
  (3, 'Intensive hands-on workshop covering AI/ML fundamentals using Python, TensorFlow, and Keras.', 'Basic Python knowledge required. Bring your own laptop with Python 3.8+.', '[{"time":"02:00 PM","activity":"Introduction to AI/ML"},{"time":"03:00 PM","activity":"Python for Data Science"},{"time":"04:00 PM","activity":"Building Your First ML Model"},{"time":"05:00 PM","activity":"Deep Learning with TensorFlow"},{"time":"06:00 PM","activity":"Q&A and Certificates"}]', '[{"place":"🏆 Best Project","reward":"Coursera Premium Subscription"},{"place":"📜 All Participants","reward":"Certificate of Completion"}]', ARRAY['Bring your own laptop', 'Python 3.8+ pre-installed'], 'Dr. Ankit Verma', '+91 76543 21098', 'coding.club@galgotias.edu.in', NULL),
  (4, '16 university teams from across NCR compete in T20 format over 4 days on our international-standard ground.', 'University cricket team members only. Valid sports ID & fitness certificate required. Max 15 per squad.', '[{"time":"07:00 AM","activity":"Team Check-in & Warm-up"},{"time":"08:00 AM","activity":"Group Stage Matches"},{"time":"12:00 PM","activity":"Lunch Break"},{"time":"02:00 PM","activity":"Afternoon Matches"}]', '[{"place":"🏆 Champions","reward":"₹1,00,000 + Trophy"},{"place":"🥈 Runners-up","reward":"₹50,000"},{"place":"⭐ Man of Tournament","reward":"₹10,000"}]', ARRAY['T20 format, ICC rules', 'White kit mandatory', 'Umpire decision is final'], 'Coach Ravi Shankar', '+91 65432 10987', 'sports@galgotias.edu.in', NULL),
  (5, 'Industry expert Mr. Varun Sethi shares insights on smart contracts, DeFi, NFTs, and decentralized internet.', 'Open to all students. No prior blockchain knowledge required.', '[{"time":"11:00 AM","activity":"Welcome & Introduction"},{"time":"11:15 AM","activity":"Keynote: Blockchain Fundamentals"},{"time":"12:00 PM","activity":"Live Demo: Smart Contracts"},{"time":"12:30 PM","activity":"Panel Discussion & Q&A"},{"time":"01:00 PM","activity":"Networking Lunch"}]', '[{"place":"📜 All Attendees","reward":"Digital Certificate + 3-month Course"}]', ARRAY['Arrive 15 minutes early', 'Phones on silent during talk'], 'Amit Sharma', '+91 54321 09876', 'ecell@galgotias.edu.in', NULL),
  (6, 'The ultimate robotics battle arena! Teams design, build, and battle robots in a specially constructed arena.', 'Teams of 2–5. Robot under 25kg. Open to all engineering students.', '[{"time":"10:00 AM","activity":"Robot Inspection & Weigh-in"},{"time":"11:00 AM","activity":"Opening Ceremony"},{"time":"11:30 AM","activity":"Lightweight Battles"},{"time":"02:30 PM","activity":"Heavyweight Battles"},{"time":"04:30 PM","activity":"Finals & Prize Ceremony"}]', '[{"place":"🏆 Champion","reward":"₹30,000 + Trophy"},{"place":"🥈 Runner-up","reward":"₹15,000"},{"place":"🎨 Best Design","reward":"₹5,000"}]', ARRAY['Weight limit: 25kg', 'No untethered projectiles', 'Safety gear mandatory'], 'Prof. Mehta', '+91 43210 98765', 'robotics@galgotias.edu.in', NULL),
  (7, 'Sunrise campus walk led by professional photographer Ankit Rathore.', 'Open to all. Bring camera or smartphone. Comfortable shoes recommended.', '[{"time":"06:00 AM","activity":"Meet at Main Gate"},{"time":"06:30 AM","activity":"Sunrise Shoot Session"},{"time":"07:30 AM","activity":"Architecture Hunt"},{"time":"08:30 AM","activity":"Photo Review & Tips"},{"time":"09:00 AM","activity":"Breakfast & Voting"}]', '[{"place":"📸 Best Photo","reward":"Yearbook Feature + ₹3,000"},{"place":"🎨 Most Creative","reward":"₹2,000"}]', ARRAY['No drones without permission', 'Respect private areas', 'Submit photos by 6 PM'], 'Arjun Mehta', '+91 32109 87654', 'camcircle@galgotias.edu.in', NULL),
  (8, 'Present your business idea to angel investors, VCs, and industry mentors. 7-minute pitch + 5-minute Q&A.', 'Teams of 1–4. Submit 1-page pitch deck 3 days before event.', '[{"time":"05:00 PM","activity":"Registration & Networking"},{"time":"05:30 PM","activity":"Keynote by Guest Investor"},{"time":"06:00 PM","activity":"Pitch Round 1"},{"time":"07:30 PM","activity":"Pitch Round 2"},{"time":"08:30 PM","activity":"Results & Awards"}]', '[{"place":"🥇 1st Place","reward":"₹2,00,000 Seed Funding + Incubation"},{"place":"🥈 2nd Place","reward":"₹1,00,000 + Mentorship"},{"place":"🥉 3rd Place","reward":"₹50,000"}]', ARRAY['7-minute pitch limit', '5-min Q&A per team', 'Pitch deck mandatory'], 'Prof. Sunita Sharma', '+91 21098 76543', 'ecell@galgotias.edu.in', NULL),
  (9, 'Ultimate test of algorithmic thinking — solve 8 problems in 3 hours.', 'Open to all. Individual only. Basic programming knowledge required.', '[{"time":"02:00 PM","activity":"Contest Begins"},{"time":"03:30 PM","activity":"Leaderboard Freeze"},{"time":"05:00 PM","activity":"Contest Ends"},{"time":"05:30 PM","activity":"Solutions & Prizes"}]', '[{"place":"🥇 1st","reward":"₹10,000 + Coding Kit"},{"place":"🥈 2nd","reward":"₹7,000"},{"place":"🥉 3rd","reward":"₹3,000"}]', ARRAY['Individual only', 'No external help', 'Any language allowed'], 'Vikram Reddy', '+91 98765 11111', 'coding.club@galgotias.edu.in', NULL),
  (10, 'TT Hustle 2.0 features Singles, Doubles, and Mixed Doubles on 8 professional ITTF tables.', 'Open to all students with valid ID. Individual and team registrations.', '[{"time":"10:00 AM","activity":"Registration & Seeding"},{"time":"11:00 AM","activity":"Round of 64"},{"time":"10:00 AM (Day 2)","activity":"Quarterfinals"},{"time":"02:00 PM (Day 2)","activity":"Doubles Category"},{"time":"10:00 AM (Day 3)","activity":"Semi-Finals & Finals"}]', '[{"place":"🏓 Singles Champion","reward":"₹15,000 + Trophy"},{"place":"🏓 Doubles","reward":"₹10,000"},{"place":"🤝 Best Sportsmanship","reward":"₹3,000"}]', ARRAY['ITTF rules apply', 'Best of 5 sets', 'Report 15 min before match'], 'Saurav Kumar', '+91 87654 22222', 'sports@galgotias.edu.in', NULL),
  (11, '2-day intensive covering AWS, Azure, and GCP. Day 1: cloud architecture. Day 2: serverless, containers, CI/CD.', 'Basic programming preferred. Bring laptop. All departments welcome.', '[{"time":"10:00 AM","activity":"Cloud Fundamentals"},{"time":"12:00 PM","activity":"Hands-on: Launch Your First VM"},{"time":"02:00 PM","activity":"Storage & Databases"},{"time":"10:00 AM (Day 2)","activity":"Serverless & Containers"},{"time":"02:00 PM (Day 2)","activity":"CI/CD Pipeline"}]', '[{"place":"📜 All Participants","reward":"$100 Cloud Credits + Certificate"},{"place":"🏆 Best Project","reward":"Certification Voucher (₹15,000)"}]', ARRAY['Bring laptop with Chrome', 'Create free-tier accounts beforehand'], 'Dr. Priya Verma', '+91 76543 33333', 'tech.society@galgotias.edu.in', NULL),
  (12, 'TEDxGalgotias 2026 theme: "Breaking Boundaries". 8 speakers from tech, social activism, science, and arts.', 'Open to all students & faculty. Valid ID required. Business formal dress code.', '[{"time":"09:30 AM","activity":"Doors Open & Coffee"},{"time":"10:00 AM","activity":"Welcome & Opening"},{"time":"10:15 AM","activity":"Session 1 (3 speakers)"},{"time":"11:30 AM","activity":"Networking Break"},{"time":"12:00 PM","activity":"Session 2 (3 speakers)"},{"time":"02:30 PM","activity":"Session 3 (2 speakers)"},{"time":"03:30 PM","activity":"Closing & Group Photo"}]', '[{"place":"📜 All Attendees","reward":"TEDx Certificate + Merchandise"}]', ARRAY['No photography during talks', 'Phones on silent', 'Arrive 30 min early', 'Business formal'], 'Ananya Singh', '+91 65432 44444', 'tedx@galgotias.edu.in', NULL);


-- ─────────────────────────────────────────────────
-- FEEDBACK SETTINGS (enable for completed events)
-- ─────────────────────────────────────────────────
INSERT INTO public.feedback_settings (event_id, enabled) VALUES
  (9, true),   -- CodeSprint Challenge
  (10, true);  -- TT Hustle 2.0
