-- Seed event_details table with extended event info
-- Run this in Supabase Dashboard → SQL Editor

INSERT INTO public.event_details (event_id, long_description, eligibility, schedule, prizes, rules, coordinator_name, coordinator_phone, coordinator_email, whatsapp_group) VALUES

(1,
 'HackGU 2026 is the flagship hackathon of Galgotias University, bringing together 500+ brilliant minds to build innovative solutions over 36 non-stop hours. Teams of 2–4 create working prototypes across HealthTech, EdTech, FinTech, and Sustainability. Industry mentors from Google, Microsoft, and Amazon guide teams. Top projects receive cash prizes, internship offers, and incubation support at the GU Innovation Hub.',
 'Open to all current students. Teams of 2–4 members from any department. At least one member with coding experience required.',
 '[{"time":"09:00 AM","activity":"Opening Ceremony & Theme Reveal"},{"time":"10:00 AM","activity":"Hacking Begins"},{"time":"01:00 PM","activity":"Lunch Break & Networking"},{"time":"06:00 PM","activity":"Mentor Sessions Round 1"},{"time":"09:00 PM","activity":"Midnight Snacks & Energy Boosters"},{"time":"09:00 AM (Day 2)","activity":"Final Submissions"},{"time":"11:00 AM (Day 2)","activity":"Judging & Presentations"},{"time":"02:00 PM (Day 2)","activity":"Prize Distribution & Closing"}]'::jsonb,
 '[{"place":"🥇 1st Place","reward":"₹50,000 + Internship Offers"},{"place":"🥈 2nd Place","reward":"₹30,000 + Goodies"},{"place":"🥉 3rd Place","reward":"₹15,000 + Certificates"},{"place":"🎨 Best UI/UX","reward":"₹5,000 Special Prize"}]'::jsonb,
 ARRAY['Teams of 2–4 members only','All code must be written during the hackathon','Open-source libraries permitted','One submission per team','Plagiarism = disqualification','Judges decision is final'],
 'Rahul Kapoor', '+91 98765 43210', 'hackgu@galgotias.edu.in', 'https://chat.whatsapp.com/hackgu2026'),

(2,
 'Crescendo is the annual 3-day cultural fest — a vibrant celebration of art, music, dance, fashion, and theatre. With 20+ competitions, celebrity performances, workshops, and food court, it transforms the campus into a carnival. Past headliners include Arijit Singh, KR$NA, and Ritviz. Students from 50+ colleges participate, making it one of the largest inter-college fests in NCR.',
 'Open to all students with valid university ID. Inter-college participants welcome with prior registration.',
 '[{"time":"10:00 AM","activity":"Inauguration & Lamp Lighting"},{"time":"11:00 AM","activity":"Battle of Bands (Prelims)"},{"time":"02:00 PM","activity":"Street Play Competition"},{"time":"04:00 PM","activity":"Fashion Show"},{"time":"07:00 PM","activity":"DJ Night & Celebrity Performance"}]'::jsonb,
 '[{"place":"🎸 Best Band","reward":"₹25,000"},{"place":"💃 Best Dance Crew","reward":"₹20,000"},{"place":"🎭 Best Actor","reward":"₹10,000"}]'::jsonb,
 ARRAY['Carry university ID at all times','No outside food or beverages','Follow event-specific rules','Respect all performers'],
 'Sneha Joshi', '+91 87654 32109', 'crescendo@galgotias.edu.in', null),

(3,
 'Intensive hands-on workshop covering AI/ML fundamentals using Python, TensorFlow, and Keras. Learn supervised/unsupervised learning, neural networks, and deep learning with real Kaggle datasets. Build and deploy your own ML model by end of day. Certificate of completion for all attendees.',
 'Basic Python knowledge required. Bring your own laptop with Python 3.8+. All departments welcome.',
 '[{"time":"02:00 PM","activity":"Introduction to AI/ML"},{"time":"03:00 PM","activity":"Python for Data Science (Hands-on)"},{"time":"04:00 PM","activity":"Building Your First ML Model"},{"time":"05:00 PM","activity":"Deep Learning with TensorFlow"},{"time":"06:00 PM","activity":"Q&A and Certificates"}]'::jsonb,
 '[{"place":"🏆 Best Project","reward":"Coursera Premium Subscription"},{"place":"📜 All Participants","reward":"Certificate of Completion"}]'::jsonb,
 ARRAY['Bring your own laptop','Python 3.8+ pre-installed','No recording without permission'],
 'Dr. Ankit Verma', '+91 76543 21098', 'coding.club@galgotias.edu.in', null),

(4,
 '16 university teams from across NCR compete in T20 format over 4 days on our international-standard ground with floodlights. Professional umpires, live scoring, and commentary ensure a world-class experience. Last year''s champion — Galgotias XI — defends their title.',
 'University cricket team members only. Valid sports ID & fitness certificate required. Max 15 per squad.',
 '[{"time":"07:00 AM","activity":"Team Check-in & Warm-up"},{"time":"08:00 AM","activity":"Group Stage Matches"},{"time":"12:00 PM","activity":"Lunch Break"},{"time":"02:00 PM","activity":"Afternoon Matches"},{"time":"06:00 PM","activity":"Day Highlights"}]'::jsonb,
 '[{"place":"🏆 Champions","reward":"₹1,00,000 + Trophy"},{"place":"🥈 Runners-up","reward":"₹50,000"},{"place":"⭐ Man of Tournament","reward":"₹10,000"}]'::jsonb,
 ARRAY['T20 format, ICC rules','White kit mandatory','No sledging','Umpire decision is final'],
 'Coach Ravi Shankar', '+91 65432 10987', 'sports@galgotias.edu.in', null),

(5,
 'Industry expert Mr. Varun Sethi shares insights on smart contracts, DeFi, NFTs, and decentralized internet. Interactive Q&A included. Free access to 3-month blockchain course for all participants.',
 'Open to all students. No prior blockchain knowledge required.',
 '[{"time":"11:00 AM","activity":"Welcome & Introduction"},{"time":"11:15 AM","activity":"Keynote: Blockchain Fundamentals"},{"time":"12:00 PM","activity":"Live Demo: Smart Contracts"},{"time":"12:30 PM","activity":"Panel Discussion & Q&A"},{"time":"01:00 PM","activity":"Networking Lunch"}]'::jsonb,
 '[{"place":"📜 All Attendees","reward":"Digital Certificate + 3-month Course"}]'::jsonb,
 ARRAY['Arrive 15 minutes early','Phones on silent during talk','Questions during Q&A only'],
 'Amit Sharma', '+91 54321 09876', 'ecell@galgotias.edu.in', null),

(6,
 'The ultimate robotics battle arena! Teams design, build, and battle robots in a specially constructed arena. Categories: Heavyweight, Lightweight, and Autonomous. Previous seasons featured flamethrowers, pneumatic flippers, and spinning blades. Safety equipment provided.',
 'Teams of 2–5. Robot under 25kg. Open to all engineering students.',
 '[{"time":"10:00 AM","activity":"Robot Inspection & Weigh-in"},{"time":"11:00 AM","activity":"Opening Ceremony"},{"time":"11:30 AM","activity":"Lightweight Battles"},{"time":"02:30 PM","activity":"Heavyweight Battles"},{"time":"04:30 PM","activity":"Finals & Prize Ceremony"}]'::jsonb,
 '[{"place":"🏆 Champion","reward":"₹30,000 + Trophy"},{"place":"🥈 Runner-up","reward":"₹15,000"},{"place":"🎨 Best Design","reward":"₹5,000"}]'::jsonb,
 ARRAY['Weight limit: 25kg','No untethered projectiles','Safety gear mandatory','Match: 3 minutes'],
 'Prof. Mehta', '+91 43210 98765', 'robotics@galgotias.edu.in', null),

(7,
 'Sunrise campus walk led by professional photographer Ankit Rathore. Tips on composition, lighting, and mobile photography. Best photos featured in the university yearbook. Bring DSLR or smartphone — all levels welcome!',
 'Open to all. Bring camera or smartphone. Comfortable shoes recommended.',
 '[{"time":"06:00 AM","activity":"Meet at Main Gate"},{"time":"06:30 AM","activity":"Sunrise Shoot Session"},{"time":"07:30 AM","activity":"Architecture Hunt"},{"time":"08:30 AM","activity":"Photo Review & Tips"},{"time":"09:00 AM","activity":"Breakfast & Voting"}]'::jsonb,
 '[{"place":"📸 Best Photo","reward":"Yearbook Feature + ₹3,000"},{"place":"🎨 Most Creative","reward":"₹2,000"}]'::jsonb,
 ARRAY['No drones without permission','Respect private areas','Submit photos by 6 PM'],
 'Arjun Mehta', '+91 32109 87654', 'camcircle@galgotias.edu.in', null),

(8,
 'Present your business idea to angel investors, VCs, and industry mentors. 7-minute pitch + 5-minute Q&A. Top 3 get seed funding, incubation space, and 6-month mentorship. Previous winners raised Series A!',
 'Teams of 1–4. Submit 1-page pitch deck 3 days before event.',
 '[{"time":"05:00 PM","activity":"Registration & Networking"},{"time":"05:30 PM","activity":"Keynote by Guest Investor"},{"time":"06:00 PM","activity":"Pitch Round 1"},{"time":"07:30 PM","activity":"Pitch Round 2"},{"time":"08:30 PM","activity":"Results & Awards"}]'::jsonb,
 '[{"place":"🥇 1st Place","reward":"₹2,00,000 Seed Funding + Incubation"},{"place":"🥈 2nd Place","reward":"₹1,00,000 + Mentorship"},{"place":"🥉 3rd Place","reward":"₹50,000"}]'::jsonb,
 ARRAY['7-minute pitch limit','5-min Q&A per team','Pitch deck mandatory','Original ideas only'],
 'Prof. Sunita Sharma', '+91 21098 76543', 'ecell@galgotias.edu.in', null),

(9,
 'Ultimate test of algorithmic thinking — solve 8 problems in 3 hours spanning data structures, DP, graphs, and math. Real-time leaderboard. Top coders earn Hall of Fame recognition.',
 'Open to all. Individual only. Basic programming knowledge required.',
 '[{"time":"02:00 PM","activity":"Contest Begins"},{"time":"03:30 PM","activity":"Leaderboard Freeze"},{"time":"05:00 PM","activity":"Contest Ends"},{"time":"05:30 PM","activity":"Solutions & Prizes"}]'::jsonb,
 '[{"place":"🥇 1st","reward":"₹10,000 + Coding Kit"},{"place":"🥈 2nd","reward":"₹7,000"},{"place":"🥉 3rd","reward":"₹3,000"}]'::jsonb,
 ARRAY['Individual only','No external help','Any language allowed','Internet restricted to contest platform'],
 'Vikram Reddy', '+91 98765 11111', 'coding.club@galgotias.edu.in', null),

(10,
 'TT Hustle 2.0 features Singles, Doubles, and Mixed Doubles on 8 professional ITTF tables. Live commentary, instant replays on big screen. 320+ players over 3 days in the Main Atrium.',
 'Open to all students with valid ID. Individual and team registrations.',
 '[{"time":"10:00 AM","activity":"Registration & Seeding"},{"time":"11:00 AM","activity":"Round of 64"},{"time":"10:00 AM (Day 2)","activity":"Quarterfinals"},{"time":"02:00 PM (Day 2)","activity":"Doubles Category"},{"time":"10:00 AM (Day 3)","activity":"Semi-Finals & Finals"}]'::jsonb,
 '[{"place":"🏓 Singles Champion","reward":"₹15,000 + Trophy"},{"place":"🏓 Doubles","reward":"₹10,000"},{"place":"🤝 Best Sportsmanship","reward":"₹3,000"}]'::jsonb,
 ARRAY['ITTF rules apply','Best of 5 sets','Report 15 min before match','No coaching during matches'],
 'Saurav Kumar', '+91 87654 22222', 'sports@galgotias.edu.in', null),

(11,
 '2-day intensive covering AWS, Azure, and GCP. Day 1: cloud architecture, VMs, storage. Day 2: serverless, containers, CI/CD. Free $100 cloud credits + certification prep material.',
 'Basic programming preferred. Bring laptop. All departments welcome.',
 '[{"time":"10:00 AM","activity":"Cloud Fundamentals"},{"time":"12:00 PM","activity":"Hands-on: Launch Your First VM"},{"time":"02:00 PM","activity":"Storage & Databases"},{"time":"10:00 AM (Day 2)","activity":"Serverless & Containers"},{"time":"02:00 PM (Day 2)","activity":"CI/CD Pipeline"}]'::jsonb,
 '[{"place":"📜 All Participants","reward":"$100 Cloud Credits + Certificate"},{"place":"🏆 Best Project","reward":"Certification Voucher (₹15,000)"}]'::jsonb,
 ARRAY['Bring laptop with Chrome','Create free-tier accounts beforehand'],
 'Dr. Priya Verma', '+91 76543 33333', 'tech.society@galgotias.edu.in', null),

(12,
 'TEDxGalgotias 2026 theme: "Breaking Boundaries". 8 speakers from tech, social activism, science, and arts. 18-minute talks, networking breaks, innovation showcase, and ideation workshop. Limited to 500 seats.',
 'Open to all students & faculty. Valid ID required. Business formal dress code.',
 '[{"time":"09:30 AM","activity":"Doors Open & Coffee"},{"time":"10:00 AM","activity":"Welcome & Opening"},{"time":"10:15 AM","activity":"Session 1 (3 speakers)"},{"time":"11:30 AM","activity":"Networking Break"},{"time":"12:00 PM","activity":"Session 2 (3 speakers)"},{"time":"02:30 PM","activity":"Session 3 (2 speakers)"},{"time":"03:30 PM","activity":"Closing & Group Photo"}]'::jsonb,
 '[{"place":"📜 All Attendees","reward":"TEDx Certificate + Merchandise"}]'::jsonb,
 ARRAY['No photography during talks','Phones on silent','Arrive 30 min early','Business formal'],
 'Ananya Singh', '+91 65432 44444', 'tedx@galgotias.edu.in', null)

ON CONFLICT (event_id) DO UPDATE SET
  long_description = EXCLUDED.long_description,
  eligibility = EXCLUDED.eligibility,
  schedule = EXCLUDED.schedule,
  prizes = EXCLUDED.prizes,
  rules = EXCLUDED.rules,
  coordinator_name = EXCLUDED.coordinator_name,
  coordinator_phone = EXCLUDED.coordinator_phone,
  coordinator_email = EXCLUDED.coordinator_email,
  whatsapp_group = EXCLUDED.whatsapp_group;
